/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/confirm': RouteRecordInfo<'/confirm', '/confirm', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/client/[id]': RouteRecordInfo<'/dashboard/client/[id]', '/dashboard/client/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/clients': RouteRecordInfo<'/dashboard/clients', '/dashboard/clients', Record<never, never>, Record<never, never>>,
    '/dashboard/invoice': RouteRecordInfo<'/dashboard/invoice', '/dashboard/invoice', Record<never, never>, Record<never, never>>,
    '/dashboard/pricing': RouteRecordInfo<'/dashboard/pricing', '/dashboard/pricing', Record<never, never>, Record<never, never>>,
    '/dashboard/profile': RouteRecordInfo<'/dashboard/profile', '/dashboard/profile', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/success': RouteRecordInfo<'/success', '/success', Record<never, never>, Record<never, never>>,
  }
}
